export const productsList = [

        {
           "id": 1, 
            "nombre": "Nombre de producto 1",
            "category":'cajaDelMes',
            "outstanding": true,
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 500,
        },
        {
           "id": 2,
            "nombre": 'Nombre de producto 2',
            "category":'porTemporada',
            "outstanding": true,
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 3,
            "nombre": 'Nombre de producto 3',
            "category":'sorpresa',
            "outstanding": true,
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 200,
        },
        {
           "id": 4,
            "category":'promociones',
            outstanding: true,
            "nombre": 'Nombre de producto 4',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 300,
        },
        {
           "id": 5,
            "category":'cajaDelMes',
            "nombre": 'Nombre de producto 5',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 300,
        },
        {
           "id": 6,
            "category":'cajaDelMes',
            "nombre": 'Nombre de producto 6',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 300,
        },
        {
           "id": 7,
            "category":'cajaDelMes',
            "nombre": 'Nombre de producto 7',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 300,
        },
        {
           "id": 8,
            "category":'porTemporada',
            "nombre": 'Nombre de producto 8',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 9,
            "category":'porTemporada',
            "nombre": 'Nombre de producto 9',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 250,
        },
        {
           "id": 10,
            "category":'porTemporada',
            "nombre": 'Nombre de producto 10',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 300,
        },
        {
           "id": 11,
            "category":'sorpresa',
            "nombre": 'Nombre de producto 11',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 500,
        },
        {
           "id": 12,
            "category":'sorpresa',
            "nombre": 'Nombre de producto 12',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 13,
            "category":'sorpresa',
            "nombre": 'Nombre de producto 13',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 14,
            "category":'promociones',
            "nombre": 'Nombre de producto 14',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 15,
            "category":'promociones',
            "nombre": 'Nombre de producto 15',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 16,
            "category":'promociones',
            "nombre": 'Nombre de producto 16',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 17,
            "category":'personalizadas',
            "nombre": 'Nombre de producto 17',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 18,
            "category":'personalizadas',
            "nombre": 'Nombre de producto 18',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 19,
            "category":'personalizadas',
            "nombre": 'Nombre de producto 19',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
        {
           "id": 20,
            "category":'personalizadas',
            "nombre": 'Nombre de producto 20',
            "img": "https://http2.mlstatic.com/D_NQ_NP_944881-MLM41810151952_052020-W.jpg",
            "descrip": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quibusdam similique unde quod, laudantium, perferendis voluptas nemo in esse obcaecati officiis nihil debitis. Deleniti ipsa fuga aliquid voluptatem quia! Mollitia",
            "color":"color del producto",
            "precio": 800,
        },
    
  ]